use std::collections::HashMap;
use std::env;

use anyhow::{Context, Result, bail};
use chrono::Utc;
use message::Message;
use provider::{CompletionRequest, Provider, SystemMessage};
use serde::{Deserialize, Serialize};

use crate::retry::RetryPolicy;
use crate::task::OmtTask;

/// Raw plan item as generated by the LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlanItem {
    pub name: String,
    pub prompt: String,
    #[serde(default = "default_agent")]
    pub agent: String,
    #[serde(default)]
    pub depends_on: Vec<String>,
    /// Relative complexity estimate (1-5). Defaults to 3.
    #[serde(default = "default_complexity")]
    pub complexity: u32,
}

fn default_agent() -> String {
    "orchestrator".to_string()
}

fn default_complexity() -> u32 {
    3
}

const PLANNER_SYSTEM: &str = r#"You are a task planner for a parallel coding agent orchestrator called omt.
Given a user request, decompose it into independent sub-tasks that can be executed in parallel where possible.

Rules:
- Each task gets its own git worktree and runs an isolated coding agent.
- Tasks that depend on another's output must list that task in depends_on.
- Keep tasks as independent as possible to maximize parallelism.
- Each task should be self-contained with a clear, specific prompt.
- Use descriptive short names (snake_case).
- If the request is already a single atomic task, return exactly one task.

Respond with ONLY a JSON array of objects:
[
  {
    "name": "task_name",
    "prompt": "Detailed instructions for this specific sub-task...",
    "agent": "orchestrator",
    "depends_on": ["other_task_name"],
    "complexity": 3
  }
]

The "complexity" field is an integer from 1 to 5 estimating relative token cost:
  1 = trivial (config changes, simple renames)
  2 = small (single function/test)
  3 = medium (module-level changes)
  4 = large (cross-module refactoring)
  5 = very large (major feature, many files)

No markdown fences, no explanation — just the JSON array."#;

/// Generate a task plan from a user prompt.
///
/// 1. If the prompt is valid JSON `Vec<PlanItem>`, use it directly (escape hatch).
/// 2. Otherwise, call the LLM to decompose the prompt into parallel tasks.
/// 3. If no provider is configured, fall back to a single-task plan.
pub async fn plan(prompt: &str) -> Result<Vec<OmtTask>> {
    // Escape hatch: direct JSON plan
    if let Ok(items) = serde_json::from_str::<Vec<PlanItem>>(prompt) {
        return items_to_tasks(&items);
    }

    // Try LLM planning
    match build_provider() {
        Ok(provider) => plan_with_llm(provider.as_ref(), prompt).await,
        Err(e) => {
            tracing::warn!("no LLM provider available ({e:#}), falling back to single task");
            let items = vec![PlanItem {
                name: "main".to_string(),
                prompt: prompt.to_string(),
                agent: "orchestrator".to_string(),
                depends_on: vec![],
                complexity: 3,
            }];
            items_to_tasks(&items)
        }
    }
}

async fn plan_with_llm(provider: &dyn Provider, prompt: &str) -> Result<Vec<OmtTask>> {
    let request = CompletionRequest {
        model: provider.default_model(),
        system: vec![SystemMessage {
            content: PLANNER_SYSTEM.to_string(),
            cache_control: false,
        }],
        messages: vec![Message::user("plan-req", prompt)],
        tools: vec![],
        temperature: Some(0.0),
        max_tokens: Some(4096),
        effort: provider::Effort::Default,
    };

    let resp = provider
        .complete(request)
        .await
        .context("LLM planning call failed")?;

    let text = resp.message.text();
    // Strip markdown fences if the model adds them despite instructions
    let json_text = strip_markdown_fences(&text);

    let items: Vec<PlanItem> = serde_json::from_str(json_text)
        .with_context(|| format!("failed to parse LLM plan response:\n{text}"))?;

    if items.is_empty() {
        bail!("LLM returned an empty plan");
    }

    items_to_tasks(&items)
}

fn strip_markdown_fences(s: &str) -> &str {
    let trimmed = s.trim();
    if let Some(rest) = trimmed.strip_prefix("```json") {
        rest.strip_suffix("```").unwrap_or(rest).trim()
    } else if let Some(rest) = trimmed.strip_prefix("```") {
        rest.strip_suffix("```").unwrap_or(rest).trim()
    } else {
        trimmed
    }
}

/// Credentials file format (compatible with omh's credentials.json).
#[derive(Debug, Deserialize)]
struct Credentials {
    providers: HashMap<String, ProviderCredential>,
}

#[derive(Debug, Deserialize)]
struct ProviderCredential {
    provider_type: String,
    api_key: String,
    base_url: Option<String>,
    model: Option<String>,
}

/// Build a provider from env vars or the omh credentials file.
fn build_provider() -> Result<Box<dyn Provider>> {
    // 1. Check env vars
    if let Ok(key) = env::var("OPENAI_API_KEY") {
        let base_url =
            env::var("OPENAI_BASE_URL").unwrap_or_else(|_| "https://api.openai.com".to_string());
        let model = env::var("OPENAI_MODEL").unwrap_or_else(|_| "gpt-4.1".to_string());
        return Ok(Box::new(
            provider::openai_compat::OpenAICompatProvider::new(
                reqwest::Client::new(),
                base_url,
                key,
                model,
            ),
        ));
    }

    if let Ok(key) = env::var("ANTHROPIC_API_KEY") {
        let model = env::var("ANTHROPIC_MODEL").unwrap_or_else(|_| "claude-sonnet-4-0".to_string());
        return Ok(Box::new(provider::anthropic::AnthropicProvider::new(
            reqwest::Client::new(),
            key,
            model,
        )));
    }

    // 2. Fall back to omh credentials file (~/.cache/omh/credentials.json)
    let creds_path = dirs::cache_dir().join("credentials.json");
    if creds_path.exists() {
        let content = std::fs::read_to_string(&creds_path)
            .with_context(|| format!("failed to read {}", creds_path.display()))?;
        let creds: Credentials = serde_json::from_str(&content)
            .with_context(|| format!("failed to parse {}", creds_path.display()))?;

        for (name, cred) in &creds.providers {
            match cred.provider_type.as_str() {
                "openai" | "custom" => {
                    let base_url = cred
                        .base_url
                        .clone()
                        .unwrap_or_else(|| "https://api.openai.com".to_string());
                    let model = cred.model.clone().unwrap_or_else(|| "gpt-4.1".to_string());
                    return Ok(Box::new(
                        provider::openai_compat::OpenAICompatProvider::new(
                            reqwest::Client::new(),
                            base_url,
                            cred.api_key.clone(),
                            model,
                        ),
                    ));
                }
                "anthropic" => {
                    let model = cred
                        .model
                        .clone()
                        .unwrap_or_else(|| "claude-sonnet-4-0".to_string());
                    return Ok(Box::new(provider::anthropic::AnthropicProvider::new(
                        reqwest::Client::new(),
                        cred.api_key.clone(),
                        model,
                    )));
                }
                "copilot" => {
                    return Ok(Box::new(provider::copilot::CopilotProvider::new(
                        cred.api_key.clone(),
                        cred.model.clone(),
                    )));
                }
                other => {
                    tracing::debug!("skipping unknown provider type '{other}' for '{name}'");
                }
            }
        }
    }

    bail!("no LLM provider configured — set OPENAI_API_KEY or ANTHROPIC_API_KEY, or run `omh auth`")
}

/// Convert plan items to OmtTask instances with ULID IDs.
fn items_to_tasks(items: &[PlanItem]) -> Result<Vec<OmtTask>> {
    // Build name → id mapping
    let mut name_to_id = std::collections::HashMap::new();
    let mut tasks = Vec::with_capacity(items.len());

    let policy = RetryPolicy::with_task_count(items.len());

    // Budget allocation: proportional to complexity
    let total_budget = env::var("OMT_TOKEN_BUDGET")
        .ok()
        .and_then(|s| s.parse::<u64>().ok())
        .unwrap_or(0);
    let total_complexity: u32 = items.iter().map(|i| i.complexity.clamp(1, 5)).sum();

    for item in items {
        let id = ulid::Ulid::new().to_string().to_ascii_lowercase();
        name_to_id.insert(item.name.clone(), id.clone());

        let task_budget = if total_budget > 0 && total_complexity > 0 {
            let c = item.complexity.clamp(1, 5) as u64;
            total_budget * c / total_complexity as u64
        } else {
            0
        };

        tasks.push(OmtTask {
            id,
            name: item.name.clone(),
            prompt: item.prompt.clone(),
            agent: item.agent.clone(),
            state: crate::task::TaskState::Pending,
            depends_on: vec![], // filled in below
            worktree_path: None,
            session_id: None,
            result: None,
            attempt_count: 0,
            max_attempts: policy.max_attempts,
            last_error: None,
            next_retry_at: None,
            created_at: Some(Utc::now()),
            started_at: None,
            completed_at: None,
            token_budget: task_budget,
            input_tokens: 0,
            output_tokens: 0,
        });
    }

    // Resolve depends_on from names to IDs
    for (i, item) in items.iter().enumerate() {
        for dep_name in &item.depends_on {
            let dep_id = name_to_id.get(dep_name).with_context(|| {
                format!(
                    "task '{}' depends on unknown task '{}'",
                    item.name, dep_name
                )
            })?;
            tasks[i].depends_on.push(dep_id.clone());
        }
    }

    Ok(tasks)
}

/// Print the plan for user review.
pub fn print_plan(tasks: &[OmtTask]) {
    eprintln!(
        "\n── Plan ({} task{}) ──",
        tasks.len(),
        if tasks.len() == 1 { "" } else { "s" }
    );
    for (i, task) in tasks.iter().enumerate() {
        let deps = if task.depends_on.is_empty() {
            String::new()
        } else {
            // Find dep names
            let dep_names: Vec<&str> = task
                .depends_on
                .iter()
                .filter_map(|dep_id| {
                    tasks
                        .iter()
                        .find(|t| t.id == *dep_id)
                        .map(|t| t.name.as_str())
                })
                .collect();
            format!(" (after: {})", dep_names.join(", "))
        };
        eprintln!("  {}. [{}] {}{}", i + 1, task.agent, task.name, deps,);
        eprintln!("     {}", truncate_prompt(&task.prompt, 80));
    }
    eprintln!();
}

fn truncate_prompt(s: &str, max: usize) -> String {
    let first_line = s.lines().next().unwrap_or(s);
    if first_line.len() <= max {
        first_line.to_string()
    } else {
        format!("{}...", &first_line[..max])
    }
}
